apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: views
          emptyDir: {}
      securityContext:
        fsGroup: 82
      # initContainers:
      #   - name: database-migrations
      #     image: irvandenata/nginx
      #     imagePullPolicy: Always
      #     envFrom:
      #       - configMapRef:
      #           name: application-config
      #       - secretRef:
      #           name: application-secret
      #     command:
      #       - "php"
      #     args:
      #       - "artisan"
      #       - "migrate"
      #       - "--force"
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: irvandenata/nginx
          resources: {}
            # limits:
            #   cpu: 500m
            #   memory: 50M
          ports:
            - containerPort: 80
        - name: fpm
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          resources: {}
          image: irvandenata/php-fpm-8.2
          ports:
            - containerPort: 9000
