apiVersion: v1
kind: Secret
metadata:
    name: application-secret
type: Opaque
data:

  #  REDIS_PASSWORD: cmRzaGFyZFBhc3MxMjM=
   DB_PASSWORD: password

   APP_KEY: YmFzZTY0OnhwVDVZWkdtZWZ1TXFqVmlIODVxTE15cGxNR244WXhoQkVGcGMrVElKbTQ9
